apiVersion: apps/v1
kind: Deployment
metadata:
  name: gps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gps
  template:
    metadata:
      labels:
        app: gps
    spec:
      containers:
      - name: gps-container
        image: gps-service
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
